spring:
  application:
    name: chat-ms
  redis:
    host: redis-master.default
    port: 6379
    broker:
      topic: notif-topic

user-ms:
  url: http://user-ms-service.default:8080/user-ms

server:
  port: 8081
  servlet:
    context-path: /${spring.application.name}

