spring:
  application:
    name: notification-ms
  redis:
    host: redis-master.default
    port: 6379
    broker:
      topic: notif-topic

server:
  port: 8082
  servlet:
    context-path: /${spring.application.name}
