apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: user-ms
spec:
  selector:
    matchLabels:
      app: user-ms
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: user-ms
    spec:
      containers:
        - name: user-ms
          image: services/user-0.0.1-snapshot # (normally we fetch from the image repository), here we did "eval $(minikube docker-env)" once to use our loacl
          imagePullPolicy: IfNotPresent
          env:
            - name: spring_cloud_config_import-check_enabled
              value: "false"
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster